# Generated by Django 3.2.15 on 2022-08-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20220825_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ID_number',
            field=models.CharField(default='00000', max_length=10),
        ),
    ]
